clc
clear all

load('path_0_2.mat')
load('wiki.mat')
addpath(genpath('Faces_0_2_Cropped'));

gender = zeros(length(path_images),1);
for i = 1:length(path_images)
    index = path_images(i);
    image_path_names{i} = strcat(int2str(i),'.jpg');
    gender(i) = wiki.gender(index);
end

%% Load Data

FaceData = imageDatastore(image_path_names,'Labels',gender);

%imds = imageDatastore({'street1.jpg','street2.jpg','peppers.png','corn.tif'})

%% 
% Display some of the images in the datastore. 
figure;
for i = 1:20
    subplot(4,5,i);
    imshow(FaceData.Files{i});
end

%%
% Check the number of images in each category. 
CountLabel = FaceData.countEachLabel;

%%
% |CountLabel| is a table that contains the labels and the number of images
% in each label. It shows that the datastore contains 1000 images for each
% of the digits 0-9, a total of 10000. Hence, there are 10 classes. You can
% specify the number of classes in the last fully connected layer of your
% network as the |OutputSize| parameter. The images are generated by
% applying random transformations to digit images created using different
% fonts.

%% 
% You must specify the size of the images in the input layer of the
% network. Check the size of the first image in |digitData| .
img = readimage(FaceData,1);
size(img)